
order = [12, 1, 4, 6, 11, 2, 3, 7, 9, 5, 8, 10];
names = {...
    'Beans', ...
    'Bricks', ...
    'Flowers', ...
    'Grass', ...
    'Scrap', ...
    'Carpet', ...
    'Cracks', ...
    'Gravel', ...
    'Paper', ...
    'Candy', ...
    'Metal', ...
    'Tiles', ...    
    };

Cm = squeeze(mean(mean(C, 2), 3));

figure(3)
clf
hold on
yl = ylim;
xt = 1 : numel(names);
bar(Corig(order), 0.5, 'facecolor', 0.7 * ones(1, 3))
plot(Cm(order, 1), '*', 'markersize', 10)
plot(Cm(order, 2), 'o', 'markersize', 8)
plot(Cm(order, 3), 's', 'markersize', 8)
t = text(xt, repmat(yl(1) - diff(yl)/50, 1, numel(names)), names);
set(t, 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', 'Rotation', 60)
set(gca, 'XTickLabel', '', 'XTick', xt, 'TickDir', 'out')
ylabel('Maximum cross-correlation')
legend({'Crops of original', 'conv5', 'power spectrum', 'P&S'}, 'location', 'northwest')

